apiVersion: v1
kind: Service
metadata:
  name: svc-test
spec:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - "IPv4"
    - "IPv6"
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30046
      protocol: TCP
  selector:
    chapter: service
