apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise
  namespace: dev
  labels:
    app: enterprise
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enterprise
  template:
    metadata:
      labels:
        app: enterprise
    spec:
      containers:
      - name: enterprise-ctr
        image: nigelpoulton/k8sbook:text-dev
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise
  namespace: prod
  labels:
    app: enterprise
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enterprise
  template:
    metadata:
      labels:
        app: enterprise
    spec:
      containers:
      - name: enterprise-str
        image: nigelpoulton/k8sbook:text-prod
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ent
  namespace: dev
spec:
  selector:
    app: enterprise
  ports:
  - port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ent
  namespace: prod
spec:
  selector:
    app: enterprise
  ports:
  - port: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: jump
  namespace: dev
spec:
  containers:
  - name: jump
    image: ubuntu
    tty: true
    stdin: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    


